# Generated by Django 4.1.5 on 2023-01-30 21:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(blank=True, max_length=255, null=True)),
                ('quantity', models.IntegerField(default=1)),
                ('given_price', models.IntegerField(default=0)),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('model', models.CharField(blank=True, max_length=255)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('imei', models.IntegerField(unique=True)),
                ('imei2', models.IntegerField(blank=True)),
                ('description', models.CharField(max_length=255)),
                ('loan_period', models.IntegerField()),
                ('interest_rate', models.IntegerField()),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('monthly_payment', jsonfield.fields.JSONField(blank=True, null=True)),
                ('remaining_amount', jsonfield.fields.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.clent')),
            ],
        ),
    ]
